### ISSUE TITLE
License this under something

### ISSUE THREAD

**Issue by est31** [tokio-rs/tokio-rfcs#4]
Similar to the [Rust RFCs repo](https://github.com/rust-lang/rust/issues/43461), this repo should get a proper license. This point is better settled now than later if it has tens, maybe hundreds of contributors :).

I suggest going with Apache2.0/MIT just like for the Rust RFC's repo. Does that sound okay?

**Comment by carllerche** [comment]
The repo is licensed under MIT / Apache 2.0. The readme now reflects this. Thanks.

**Comment by est31** [comment]
Thank you!
